kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: jrei/crystal-alpine
  commands:
  - apk add curl
  - shards install
  - crystal spec
  - shards build --progress --release --static
