kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: format
  image: jrei/crystal-alpine
  commands:
  - crystal tool format --check

- name: lint
  image: madscientists/ameba
  commands:
  - ameba

- name: build
  image: jrei/crystal-alpine
  commands:
  - apk add curl
  - shards install
  - shards build --static

- name: test
  image: jrei/crystal-alpine
  environment:
    KEMAL_ENV: test
  commands:
  - crystal spec
