kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: format
  image: jrei/crystal-alpine
  commands:
  - crystal tool format --check

- name: build
  image: jrei/crystal-alpine
  volumes:
  - name: cache
    path: /root/.cache
  commands:
  - crystal env
  - apk add curl
  - shards install
  - shards build --static

- name: lint
  image: jrei/crystal-alpine
  volumes:
  - name: cache
    path: /root/.cache
  commands:
  - bin/ameba

- name: test
  image: jrei/crystal-alpine
  volumes:
  - name: cache
    path: /root/.cache
  commands:
  - crystal spec

volumes:
- name: cache
  temp: {}
